

-- local haslfs,lfs = pcall(require,"telescope.extensions.file_browser.actions")
-- if haslfs then
-- fb_actions =  require('telescope.extensions.file_browser.actions').setup {}
-- else
-- end
--
-- -- local fb_actions = loadrequire("telescope.extensions.file_browser.actions")
-- -- local fb_actions = require "telescope".extensions.file_browser.actions
-- loadrequire('telescope').setup {
--   extensions = {
--     file_browser = {
--         mappings = {
--         ["i"] = {
--          -- remap to going to home directory
--           ["<C-u>"] = fb_actions.change_cwd,
--           ["<C-x>"] = function(prompt_bufnr)
--             -- your custom function
--           end
--         },
--         ["n"] = {
--           -- unmap toggling `fb_actions.toggle_browser`
--           f = false,
--         },
--       }
--     }
--   }
-- }
